/**
 * RehearsalModePanel - Section-by-section practice mode side panel
 *
 * Provides step-by-step navigation through drill sets with per-performer
 * movement instructions generated by the rehearsal service.
 */

import { useState, useMemo, useCallback } from 'react';
import {
  X,
  ChevronLeft,
  ChevronRight,
  Repeat,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowUpRight,
  ArrowDownRight,
  ArrowDownLeft,
  ArrowUpLeft,
  Minus,
} from 'lucide-react';
import type { Formation, DrillSet } from '../../services/formationTypes';
import {
  generateRehearsalPlan,
  getRehearsalSummary,
  getSections,
} from '../../services/rehearsalService';
import type { PerformerInstruction, RehearsalStep } from '../../services/rehearsalService';

// ============================================================================
// Types
// ============================================================================

export interface RehearsalModePanelProps {
  formation: Formation;
  sets: DrillSet[];
  onClose: () => void;
  onNavigateToSet: (setId: string) => void;
  onHighlightPerformers?: (ids: string[]) => void;
}

// ============================================================================
// Helpers
// ============================================================================

function DirectionArrow({ direction }: { direction: string }) {
  const iconClass = 'w-4 h-4 text-blue-500 flex-shrink-0';
  switch (direction) {
    case 'forward': return <ArrowUp className={iconClass} />;
    case 'backward': return <ArrowDown className={iconClass} />;
    case 'to the right': return <ArrowRight className={iconClass} />;
    case 'to the left': return <ArrowLeft className={iconClass} />;
    case 'forward-right': return <ArrowUpRight className={iconClass} />;
    case 'forward-left': return <ArrowUpLeft className={iconClass} />;
    case 'backward-right': return <ArrowDownRight className={iconClass} />;
    case 'backward-left': return <ArrowDownLeft className={iconClass} />;
    case 'hold': return <Minus className={iconClass} />;
    default: return <ArrowRight className={iconClass} />;
  }
}

// ============================================================================
// Component
// ============================================================================

export function RehearsalModePanel({
  formation,
  sets,
  onClose,
  onNavigateToSet,
  onHighlightPerformers,
}: RehearsalModePanelProps) {
  const [selectedSection, setSelectedSection] = useState('All');
  const [currentStepIndex, setCurrentStepIndex] = useState(0);
  const [loopEnabled, setLoopEnabled] = useState(false);

  // Available sections
  const sections = useMemo(
    () => getSections(formation.performers),
    [formation.performers],
  );

  // Generate rehearsal plan
  const steps = useMemo(
    () => generateRehearsalPlan(formation, sets, selectedSection),
    [formation, sets, selectedSection],
  );

  // Summary stats
  const summary = useMemo(() => getRehearsalSummary(steps), [steps]);

  // Current step
  const currentStep: RehearsalStep | undefined = steps[currentStepIndex];

  // Sorted performer instructions for current step
  const sortedInstructions: PerformerInstruction[] = useMemo(() => {
    if (!currentStep) return [];
    return Array.from(currentStep.performers.values()).sort((a, b) =>
      (a.drillNumber ?? a.performerName).localeCompare(b.drillNumber ?? b.performerName),
    );
  }, [currentStep]);

  // Navigation
  const goToStep = useCallback(
    (index: number) => {
      const clamped = Math.max(0, Math.min(index, steps.length - 1));
      setCurrentStepIndex(clamped);
      const step = steps[clamped];
      if (step) {
        onNavigateToSet(step.setId);
        if (onHighlightPerformers) {
          onHighlightPerformers(Array.from(step.performers.keys()));
        }
      }
    },
    [steps, onNavigateToSet, onHighlightPerformers],
  );

  const goPrev = useCallback(() => {
    if (currentStepIndex > 0) {
      goToStep(currentStepIndex - 1);
    } else if (loopEnabled && steps.length > 0) {
      goToStep(steps.length - 1);
    }
  }, [currentStepIndex, goToStep, loopEnabled, steps.length]);

  const goNext = useCallback(() => {
    if (currentStepIndex < steps.length - 1) {
      goToStep(currentStepIndex + 1);
    } else if (loopEnabled && steps.length > 0) {
      goToStep(0);
    }
  }, [currentStepIndex, goToStep, loopEnabled, steps.length]);

  return (
    <div className="w-80 h-full bg-white dark:bg-gray-800 border-l border-gray-200 dark:border-gray-700 flex flex-col overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-gray-200 dark:border-gray-700">
        <h3 className="font-semibold text-gray-900 dark:text-white text-sm">Rehearsal Mode</h3>
        <button
          onClick={onClose}
          className="p-1 rounded text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700"
          aria-label="Close rehearsal mode"
        >
          <X className="w-4 h-4" />
        </button>
      </div>

      {/* Section filter */}
      <div className="px-4 py-2 border-b border-gray-200 dark:border-gray-700">
        <label className="block text-xs font-medium text-gray-500 dark:text-gray-400 mb-1">
          Section
        </label>
        <select
          value={selectedSection}
          onChange={(e) => {
            setSelectedSection(e.target.value);
            setCurrentStepIndex(0);
          }}
          className="w-full text-sm bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-md px-2 py-1.5 text-gray-700 dark:text-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          {sections.map((s) => (
            <option key={s} value={s}>{s}</option>
          ))}
        </select>
      </div>

      {/* Navigation */}
      {steps.length > 0 && currentStep && (
        <div className="px-4 py-3 border-b border-gray-200 dark:border-gray-700">
          <div className="flex items-center justify-between mb-2">
            <button
              onClick={goPrev}
              disabled={!loopEnabled && currentStepIndex === 0}
              className="p-1.5 rounded text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 disabled:opacity-30 disabled:cursor-not-allowed"
              aria-label="Previous set"
            >
              <ChevronLeft className="w-5 h-5" />
            </button>
            <div className="text-center">
              <div className="text-sm font-medium text-gray-900 dark:text-white">
                {currentStep.setName}
              </div>
              <div className="text-xs text-gray-500 dark:text-gray-400">
                {currentStep.counts} counts
                {currentStep.rehearsalMark && ` | ${currentStep.rehearsalMark}`}
              </div>
            </div>
            <button
              onClick={goNext}
              disabled={!loopEnabled && currentStepIndex === steps.length - 1}
              className="p-1.5 rounded text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 disabled:opacity-30 disabled:cursor-not-allowed"
              aria-label="Next set"
            >
              <ChevronRight className="w-5 h-5" />
            </button>
          </div>

          {/* Progress + Loop */}
          <div className="flex items-center justify-between">
            <span className="text-xs text-gray-500 dark:text-gray-400 tabular-nums">
              {currentStepIndex + 1} / {steps.length}
            </span>
            <button
              onClick={() => setLoopEnabled(!loopEnabled)}
              className={`flex items-center gap-1 px-2 py-0.5 rounded text-xs ${
                loopEnabled
                  ? 'bg-blue-100 dark:bg-blue-900 text-blue-600 dark:text-blue-400'
                  : 'text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700'
              }`}
              aria-pressed={loopEnabled}
              aria-label="Toggle loop"
            >
              <Repeat className="w-3 h-3" />
              Loop
            </button>
          </div>

          {/* Progress bar */}
          <div className="mt-2 h-1 bg-gray-200 dark:bg-gray-600 rounded-full overflow-hidden">
            <div
              className="h-full bg-blue-500 rounded-full transition-all duration-200"
              style={{ width: `${((currentStepIndex + 1) / steps.length) * 100}%` }}
            />
          </div>
        </div>
      )}

      {/* Performer instructions */}
      <div className="flex-1 overflow-y-auto">
        {sortedInstructions.length === 0 ? (
          <div className="px-4 py-8 text-center text-sm text-gray-400 dark:text-gray-500">
            {steps.length === 0
              ? 'Add at least 2 sets to generate rehearsal instructions.'
              : 'No performers in this section.'}
          </div>
        ) : (
          <div className="divide-y divide-gray-100 dark:divide-gray-700">
            {sortedInstructions.map((inst) => (
              <div
                key={inst.performerId}
                className="px-4 py-2.5 hover:bg-gray-50 dark:hover:bg-gray-700/50 cursor-pointer"
                onClick={() => onHighlightPerformers?.([inst.performerId])}
              >
                <div className="flex items-center justify-between mb-0.5">
                  <div className="flex items-center gap-1.5">
                    {inst.drillNumber && (
                      <span className="text-xs font-mono bg-gray-100 dark:bg-gray-700 px-1 rounded text-gray-600 dark:text-gray-400">
                        {inst.drillNumber}
                      </span>
                    )}
                    <span className="text-sm font-medium text-gray-800 dark:text-gray-200">
                      {inst.performerName}
                    </span>
                  </div>
                  <DirectionArrow direction={inst.direction} />
                </div>
                {inst.instrument && (
                  <div className="text-xs text-gray-400 dark:text-gray-500 mb-0.5">
                    {inst.instrument}
                  </div>
                )}
                <div className="text-xs text-gray-600 dark:text-gray-400">
                  {inst.instruction}
                </div>
                {inst.distanceYards > 0.1 && (
                  <div className="text-xs text-gray-400 dark:text-gray-500 mt-0.5">
                    {inst.distanceYards} yds | {inst.stepSize}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Summary footer */}
      {steps.length > 0 && (
        <div className="px-4 py-2.5 border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50">
          <div className="grid grid-cols-3 gap-2 text-center">
            <div>
              <div className="text-xs text-gray-400 dark:text-gray-500">Performers</div>
              <div className="text-sm font-medium text-gray-700 dark:text-gray-300 tabular-nums">
                {summary.totalPerformers}
              </div>
            </div>
            <div>
              <div className="text-xs text-gray-400 dark:text-gray-500">Avg Step</div>
              <div className="text-sm font-medium text-gray-700 dark:text-gray-300 tabular-nums">
                {summary.avgStepSize > 0 ? `${summary.avgStepSize}:5` : '--'}
              </div>
            </div>
            <div>
              <div className="text-xs text-gray-400 dark:text-gray-500">Sets</div>
              <div className="text-sm font-medium text-gray-700 dark:text-gray-300 tabular-nums">
                {summary.totalSets}
              </div>
            </div>
          </div>
          {summary.hardestMove && (
            <div className="mt-1.5 text-xs text-amber-600 dark:text-amber-400 text-center">
              Hardest: {summary.hardestMove.performerName} ({summary.hardestMove.distanceYards} yds at {summary.hardestMove.setName})
            </div>
          )}
        </div>
      )}
    </div>
  );
}
