import type { MaterialInfo, QualityPresetInfo } from '@/types/printing';

export const MATERIALS: MaterialInfo[] = [
  {
    id: 'PLA',
    name: 'PLA',
    description: 'Standard plastic, easy to print',
    color: 'bg-blue-500',
    properties: ['Biodegradable', 'Rigid', 'Smooth finish'],
    costPerGram: 0.02,
    hotendTemp: 200,
    bedTemp: 60,
  },
  {
    id: 'PETG',
    name: 'PETG',
    description: 'Strong and flexible',
    color: 'bg-purple-500',
    properties: ['Durable', 'Heat-resistant', 'Flexible'],
    costPerGram: 0.025,
    hotendTemp: 230,
    bedTemp: 80,
  },
  {
    id: 'ABS',
    name: 'ABS',
    description: 'Engineering-grade, very strong',
    color: 'bg-orange-500',
    properties: ['Very strong', 'Heat-resistant', 'Post-processable'],
    costPerGram: 0.022,
    hotendTemp: 240,
    bedTemp: 100,
  },
  {
    id: 'TPU',
    name: 'TPU (Flexible)',
    description: 'Rubber-like, stretchy material',
    color: 'bg-green-500',
    properties: ['Flexible', 'Shock-absorbent', 'Wear-resistant'],
    costPerGram: 0.035,
    hotendTemp: 220,
    bedTemp: 50,
  },
  {
    id: 'NYLON',
    name: 'Nylon',
    description: 'High-strength, professional',
    color: 'bg-gray-500',
    properties: ['Very strong', 'Flexible', 'Wear-resistant'],
    costPerGram: 0.04,
    hotendTemp: 250,
    bedTemp: 90,
  },
];

export const QUALITY_PRESETS: QualityPresetInfo[] = [
  {
    id: 'draft',
    name: 'Quick Draft',
    description: 'Fast prints for testing ideas',
    layerHeight: 0.3,
    infillPercentage: 10,
    speedMultiplier: 1.5,
    timeMultiplier: 0.6,
    recommended: false,
  },
  {
    id: 'standard',
    name: 'Standard Quality',
    description: 'Great for most uses',
    layerHeight: 0.2,
    infillPercentage: 20,
    speedMultiplier: 1.0,
    timeMultiplier: 1.0,
    recommended: true,
  },
  {
    id: 'high',
    name: 'High Detail',
    description: 'Smooth finish, fine features',
    layerHeight: 0.12,
    infillPercentage: 30,
    speedMultiplier: 0.8,
    timeMultiplier: 1.4,
    recommended: false,
  },
  {
    id: 'ultra',
    name: 'Exhibition Quality',
    description: 'Perfect for client presentations',
    layerHeight: 0.08,
    infillPercentage: 40,
    speedMultiplier: 0.6,
    timeMultiplier: 1.8,
    recommended: false,
  },
];
