# DigitalOcean App Platform Configuration
# FluxStudio Production Deployment
# Architecture: Static Frontend + Unified Backend + Collaboration Service + MCP
# Last synced: 2026-02-08 - Updated to use pnpm instead of npm

name: fluxstudio
region: nyc

# Reference existing PostgreSQL database
# Database ID: 49f4dc39-3d91-4bce-aa7a-7784c8e32a66

# Ingress Rules (Path-based routing)
# Note: Order matters! More specific paths should come first.
# OAuth callbacks now handled by Express CORS middleware (accepts origin: null)
ingress:
  rules:
    # API + Socket.IO routes → unified-backend
    - component:
        name: unified-backend
      match:
        path:
          prefix: /api
      cors:
        allow_origins:
          - exact: https://fluxstudio.art
          - exact: https://www.fluxstudio.art
        allow_methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - OPTIONS
        allow_headers:
          - Content-Type
          - Authorization
          - Upgrade
          - Connection
        allow_credentials: true
    # Yjs Collaboration WebSocket → collaboration service
    - component:
        name: collaboration
      match:
        path:
          prefix: /collab
      cors:
        allow_origins:
          - exact: https://fluxstudio.art
          - exact: https://www.fluxstudio.art
        allow_methods:
          - GET
          - OPTIONS
        allow_headers:
          - Content-Type
          - Authorization
          - Upgrade
          - Connection
        allow_credentials: true
    # MCP Server (Model Context Protocol)
    - component:
        name: flux-mcp
      match:
        path:
          prefix: /mcp
      cors:
        allow_origins:
          - exact: https://fluxstudio.art
          - exact: https://www.fluxstudio.art
        allow_methods:
          - GET
          - POST
          - OPTIONS
        allow_headers:
          - Content-Type
          - Authorization
          - Upgrade
          - Connection
        allow_credentials: true
    # Frontend (catch-all, must be last)
    - component:
        name: frontend
      match:
        path:
          prefix: /

# Static Frontend (Vite-built React SPA)
static_sites:
  - name: frontend
    github:
      repo: kentin0-fiz0l/FluxStudio
      branch: main
      deploy_on_push: true
    build_command: corepack enable && pnpm install --frozen-lockfile && pnpm build
    output_dir: build
    environment_slug: node-js
    catchall_document: index.html
    envs:
      - key: VITE_API_BASE_URL
        value: /api
      - key: VITE_AUTH_URL
        value: /api/auth
      - key: VITE_MESSAGING_URL
        value: /api/messaging
      - key: VITE_SOCKET_URL
        value: wss://fluxstudio.art
      - key: VITE_COLLAB_URL
        value: wss://fluxstudio.art/collab
      - key: VITE_APP_URL
        value: https://fluxstudio.art
      - key: VITE_GOOGLE_CLIENT_ID
        value: 65518208813-f4rgudom5b57qad0jlhjtsocsrb26mfc.apps.googleusercontent.com
      - key: VITE_MCP_WS_URL
        value: wss://fluxstudio.art/mcp
      - key: VITE_GITHUB_CONNECTED
        value: "true"
      - key: VITE_MCP_AUTH_TOKEN
        scope: BUILD_TIME
        type: SECRET

# Database Migration Job (runs before deployment)
jobs:
  - name: db-migrate
    github:
      repo: kentin0-fiz0l/FluxStudio
      branch: main
      deploy_on_push: true
    build_command: corepack enable && pnpm install --frozen-lockfile
    run_command: node database/run-migrations.js
    environment_slug: node-js
    kind: PRE_DEPLOY
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET

# Unified Backend (Auth + Messaging consolidated)
services:
  - name: unified-backend
    github:
      repo: kentin0-fiz0l/FluxStudio
      branch: main
      deploy_on_push: true
    build_command: corepack enable && pnpm install --frozen-lockfile
    run_command: node server-unified.js
    environment_slug: node-js
    http_port: 3001
    health_check:
      http_path: /health
      initial_delay_seconds: 120
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 5
    instance_count: 1
    instance_size_slug: professional-xs
    envs:
      # Node Environment
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"

      # Database (Existing PostgreSQL database - same as MetMap for shared accounts)
      # DATABASE_URL is set as encrypted secret in DigitalOcean dashboard
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: USE_DATABASE
        value: "true"
      - key: DB_SSL
        value: "true"

      # Redis (Valkey 8.0 - Redis-compatible cache layer)
      # REDIS_URL is set as encrypted secret in DigitalOcean dashboard
      - key: USE_REDIS
        value: "true"
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET

      # JWT Configuration (MUST BE SET AS SECRETS)
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: JWT_EXPIRY
        value: "1h"

      # Session (MUST BE SET AS SECRET)
      - key: SESSION_SECRET
        scope: RUN_TIME
        type: SECRET

      # OAuth Encryption (MUST BE SET AS SECRET)
      - key: OAUTH_ENCRYPTION_KEY
        scope: RUN_TIME
        type: SECRET

      # Google OAuth
      # Note: Client ID is public (same as frontend), but secret must be set in DO dashboard
      - key: GOOGLE_CLIENT_ID
        value: 65518208813-f4rgudom5b57qad0jlhjtsocsrb26mfc.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET

      # GitHub OAuth (MUST BE SET AS SECRETS)
      - key: GITHUB_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: GITHUB_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET

      # Figma OAuth (MUST BE SET AS SECRETS)
      - key: FIGMA_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: FIGMA_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET

      # Slack OAuth (MUST BE SET AS SECRETS)
      - key: SLACK_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: SLACK_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: SLACK_SIGNING_SECRET
        scope: RUN_TIME
        type: SECRET

      # SMTP Configuration (MUST BE SET AS SECRETS)
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        scope: RUN_TIME
        type: SECRET
      - key: SMTP_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: EMAIL_FROM
        value: noreply@fluxstudio.art

      # CORS Origins (hardcoded - App Platform doesn't interpolate ${} in runtime env vars)
      - key: CORS_ORIGINS
        value: "https://fluxstudio.art,https://www.fluxstudio.art,https://fluxstudio-frontend.ondigitalocean.app"

      # Rate Limiting
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "50"
      - key: AUTH_RATE_LIMIT_MAX
        value: "3"

      # Application Settings
      - key: APP_NAME
        value: FluxStudio
      - key: APP_URL
        value: https://fluxstudio.art
      - key: UPLOAD_DIR
        value: /tmp/uploads
      - key: MAX_FILE_SIZE
        value: "52428800"
      - key: ENABLE_REGISTRATION
        value: "true"
      - key: ENABLE_OAUTH
        value: "true"
      - key: ENABLE_FILE_UPLOAD
        value: "true"
      - key: ENABLE_WEBSOCKET
        value: "true"

      # DigitalOcean Spaces Configuration (for HLS video streaming)
      - key: SPACES_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_BUCKET
        value: fluxstudio
      - key: SPACES_ENDPOINT
        value: sfo3.digitaloceanspaces.com
      - key: SPACES_REGION
        value: sfo3

      # FluxPrint Integration (Phase 4A)
      # Set to false initially - UI will be visible but print endpoints return "Feature not enabled"
      # To enable: Deploy FluxPrint service and set FLUXPRINT_SERVICE_URL
      - key: FLUXPRINT_ENABLED
        value: "false"
      - key: FLUXPRINT_SERVICE_URL
        value: "http://localhost:5001"
      - key: SPACES_CDN
        value: https://fluxstudio.sfo3.cdn.digitaloceanspaces.com

      # Anthropic API Key (for AI Agent features)
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET

      # MCP Configuration (disable postgres until DATABASE_URL is properly set)
      - key: MCP_POSTGRES_ENABLED
        value: "false"

# Collaboration Service (Separate - uses Yjs/WebSocket, not Socket.IO)
  - name: collaboration
    github:
      repo: kentin0-fiz0l/FluxStudio
      branch: main
      deploy_on_push: true
    build_command: corepack enable && pnpm install --frozen-lockfile
    run_command: node server-collaboration.js
    environment_slug: node-js
    http_port: 4000
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    instance_count: 1
    instance_size_slug: professional-xs
    envs:
      - key: NODE_ENV
        value: production
      - key: COLLAB_PORT
        value: "4000"
      - key: COLLAB_HOST
        value: "0.0.0.0"
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: AUTH_SERVICE_URL
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET

# MCP Server (Model Context Protocol for AI integrations)
  # Using Node.js buildpack (Dockerfile detection unreliable on App Platform)
  - name: flux-mcp
    github:
      repo: kentin0-fiz0l/FluxStudio
      branch: main
      deploy_on_push: true
    source_dir: flux-mcp
    build_command: npm ci --include=dev && npm run build
    run_command: npm start
    environment_slug: node-js
    http_port: 8787
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8787"
      - key: TRANSPORT
        value: websocket
      - key: GITHUB_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: GITHUB_OWNER
        scope: RUN_TIME
        type: SECRET
      - key: GITHUB_REPO
        value: FluxStudio
      - key: GITHUB_WORKFLOW_FILE
        value: deploy.yml
      - key: MCP_AUTH_TOKEN
        scope: RUN_TIME
        type: SECRET

# FFmpeg Transcoding Worker (DISABLED - Dockerfile detection issues on App Platform)
# TODO: Re-enable when Dockerfile path resolution is fixed
# Configured as a service (not worker) because DigitalOcean App Platform requires HTTP endpoint
#  - name: ffmpeg-worker
#    github:
#      repo: kentin0-fiz0l/FluxStudio
#      branch: main
#      deploy_on_push: true
#    source_dir: services/ffmpeg-worker
#    dockerfile_path: Dockerfile
#    http_port: 8080
#    health_check:
#      http_path: /health
#      initial_delay_seconds: 10
#      period_seconds: 30
#      timeout_seconds: 5
#      success_threshold: 1
#      failure_threshold: 3
#    instance_count: 1
#    instance_size_slug: basic-xs
#    envs:
#      - key: NODE_ENV
#        value: production
#      - key: PORT
#        value: "8080"
#      - key: DATABASE_URL
#        scope: RUN_TIME
#        type: SECRET
#      - key: SPACES_ACCESS_KEY
#        scope: RUN_TIME
#        type: SECRET
#      - key: SPACES_SECRET_KEY
#        scope: RUN_TIME
#        type: SECRET
#      - key: SPACES_BUCKET
#        value: fluxstudio
#      - key: SPACES_ENDPOINT
#        value: sfo3.digitaloceanspaces.com
#      - key: SPACES_REGION
#        value: sfo3
#      - key: SPACES_CDN
#        value: https://fluxstudio.sfo3.cdn.digitaloceanspaces.com
#      - key: WORK_DIR
#        value: /tmp/transcoding
#      - key: CONCURRENT_JOBS
#        value: "1"

# Custom Domain Configuration
domains:
  - domain: fluxstudio.art
    type: PRIMARY
    zone: fluxstudio.art
  - domain: www.fluxstudio.art
    type: ALIAS
    zone: fluxstudio.art

# Monitoring & Alerts
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
